services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=travelnest'
      - 'MYSQL_PASSWORD=travelnest'
      - 'MYSQL_ROOT_PASSWORD=travelnest'
      - 'MYSQL_USER=travelnest'
    ports:
      - '3306'