version: "3.9"

services:
  db:
    container_name: travelnest_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  volumes:
    pgdata: {}
